<div id="service_list_box"><div id="output_block_header" style="width:508px; height:36px; display:inline-block;"><img src="<?php echo $sect_hdr; ?>" /></div>
<?php echo $contents; //generated by load_partial from Template Library, and is the content of the view file ?>
</div>