<?php // template file for use by view services_partial ?>
<div id="box" style="width:500px; height:200px; overflow:auto; margin-left:34px; background-color:white;">
	<div id="output_block_header" style="width:500px; height:20px;"><?php //echo $title;?></div>
	<?php //echo $contents; //generated by load_partial from Template Library, and is the content of the view file ?>
</div>