<div id="staff_list_box">
	<div id="output_block_header" style="width:918px; height:7px; display:block; margin:20px 0px;"><img src="images/grfx_pagerule.png" /></div>
	<?php echo $contents; //generated by load_partial from Template Library, and is the content of the view file ?>
</div>